package com.adarsh.pages;

import java.util.List;
import org.openqa.selenium.By;

/** Open New Account. */
public class OpenNewAccountPage extends BasePage {

    // Accepts either state of the page: the form before submit, the result panel after it.
    private static final By FORM = By.cssSelector("#openAccountForm, #openAccountResult, #openAccountError");
    private static final By ACCOUNT_TYPE = By.id("type");
    private static final By FROM_ACCOUNT = By.id("fromAccountId");
    private static final By OPEN_BUTTON = By.cssSelector("#openAccountForm input.button[value='Open New Account']");

    private static final By RESULT_PANEL = By.id("openAccountResult");
    private static final By NEW_ACCOUNT_ID = By.id("newAccountId");
    private static final By ERROR_PANEL = By.id("openAccountError");

    public enum AccountType {
        CHECKING("CHECKING"),
        SAVINGS("SAVINGS");

        private final String optionText;

        AccountType(String optionText) {
            this.optionText = optionText;
        }

        public String optionText() {
            return optionText;
        }
    }

    @Override
    protected By pageReadyLocator() {
        return FORM;
    }

    public OpenNewAccountPage() {
        verifyLoaded();
    }

    // ===== Actions =====

    public OpenNewAccountPage chooseAccountType(AccountType type) {
        selectByVisibleText(ACCOUNT_TYPE, type.optionText());
        return this;
    }

    /** The funding account list arrives over AJAX, so this waits for options before selecting. */
    public String chooseFirstFundingAccount() {
        return selectFirstOption(FROM_ACCOUNT);
    }

    public OpenNewAccountPage chooseFundingAccount(String accountNumber) {
        selectByVisibleText(FROM_ACCOUNT, accountNumber);
        return this;
    }

    public List<String> availableFundingAccounts() {
        return optionTexts(FROM_ACCOUNT);
    }

    public OpenNewAccountPage submit() {
        click(OPEN_BUTTON);
        return this;
    }

    /** Opens an account of the given type funded by the first available account. */
    public OpenNewAccountPage openAccount(AccountType type) {
        chooseAccountType(type);
        var funding = chooseFirstFundingAccount();
        log.info("Opening a {} account funded from {}", type, funding);
        return submit();
    }

    // ===== Reads =====

    public boolean isAccountOpened() {
        waitForVisible(RESULT_PANEL);
        return isDisplayed(RESULT_PANEL);
    }

    /** The new account number, which is generated by the application at runtime. */
    public String newAccountNumber() {
        waitForVisible(RESULT_PANEL);
        // The span is filled by JS a beat after the panel appears.
        waitIgnoringStaleness(d -> !d.findElement(NEW_ACCOUNT_ID).getText().isBlank());
        return textOf(NEW_ACCOUNT_ID);
    }

    public boolean hasError() {
        return isDisplayed(ERROR_PANEL);
    }

    public byte[] resultScreenshot() {
        return elementScreenshot(RESULT_PANEL);
    }
}
